version: '2'
services:
  registry-app:
    image: registry:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/sonirahul/git-config-server.git
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=docker-config
    ports:
      - 8761:8761
  mongodb:
    image: mongo:4.0.13
    ports:
      - '27017:27017'
  gateway-app:
    image: gateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://registry-app:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://registry-app:8761/config
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://registry-app:8761/admin
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=altimetrik
      - ALTIMETRIK_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    depends_on:
      - registry-app
      - mongodb
  greeting-service-app:
    image: greeting-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://registry-app:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://registry-app:8761/config
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://registry-app:8761/admin
      - ALTIMETRIK_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
    depends_on:
      - registry-app
